name: Deploy React Frontend to AWS

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust if you use a different Node version

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        # This injects your ALB link directly into the build!
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          CI: false
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3 Bucket
        # Syncs the build folder and deletes old files not in the new build
        run: aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        # Forces the CDN to fetch your new files instead of serving old cached ones
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"